---
title: "AGSTATS v2"
author: "Michael Rahija"
date: "`r format(Sys.time(),'%B %d , %Y')`"
output: pdf_document
---



```{r, echo=FALSE,fig.pos="placeHere",include=FALSE, cache=FALSE}
#create maps

#create maps and figures for analysis

#-- import data and packages
library(dplyr)
library(ggplot2)
library(countrycode)
library(tidyr)

sys <- Sys.info()

if(sys[5] == "x86_64"){
  dir = "~/Dropbox/agSTATS" #Mac
  data.dir = "~/Dropbox/agSTATS/data/" 
} else if (sys[5] == "Michael"){
  dir = "C:/Users/Michael/Dropbox/agSTATS"#HOME PC
  data.dir = "C:/Users/Michael/Dropbox/agSTATS/data/"
} else if (sys[6]=="Rahija") {
  dir = "C:/Users/rahija/Dropbox/agSTATS" #FAO PC
  data.dir = "C:/Users/rahija/Dropbox/agSTATS/data/"
} else {
  stop("Implement location for current user!")
}

setwd(dir)

data <- read.csv(paste0(data.dir,"agstats_final_for narrative_V5.csv"), 
                 stringsAsFactors = FALSE)


source("R/cleanFigures.R")
data <- cleanFigures(data)

ca <- read.csv(paste0(data.dir,"asci_scores.csv"), 
                 stringsAsFactors = FALSE)

ca$country <- countrycode(ca$country, origin = "country.name",
                          destination = "country.name")
```


# Project Type/Classification

## No of projects by type
```{r, echo = FALSE}
tab <- data %>%
            group_by(projectType) %>%
            summarize(noProject = length(unique(agId)))

knitr::kable(tab)            
```

## Total budget for each project type
```{r, echo = FALSE}
tab <- data %>%
            group_by(projectType) %>%
            summarize(totalBudget = sum(budget))

knitr::kable(tab)            
```

# Total budgets by donors

```{r, echo = FALSE}
source("R/computeDonorContrib.R")
donor <- computeDonorContrib(data)

donor$contrib <- donor$budget * donor$percent

tab <- donor %>%
            group_by(donor) %>%
            summarize(totalBudget = sum(contrib))
tab <- arrange(tab, desc(totalBudget))

knitr::kable(tab)
```

# Regional level
## Total budget by donor and region
```{r, echo = FALSE}

#merge donor table w/ data on agId
donor.region <- merge(donor, data, by = "agId", all = TRUE)

tab <- donor.region %>%
            group_by(Region, donor.x) %>%
            summarize(totalBudget = sum(contrib))

tab <- arrange(tab, Region, donor.x, totalBudget)
knitr::kable(tab)

```

## Total budget by region
```{r, echo = FALSE}
tab <- data %>%
            group_by(Region) %>%
            summarize(totalBudget = sum(budget))

tab <- arrange(tab, desc(totalBudget))
knitr::kable(tab)
```

# TOTAL BUDGET, BY COUNTRY **SUBSET FOR assCountry = 1**
```{r, echo = FALSE}
country <- filter(data, assCountry == 1)

#--------CREATE DF FOR EXPENDITURES BY COUNTRY AND MERGE CENTROIDS

#Get expenditure data 
test.c <- colnames(country) %in% NA
country <- country[!test.c]

data.d <- select(country, country, budget, donor)
data.d <- filter(data.d, !is.na(budget))

x <- strsplit(data.d$country,",")

data.d$denom <- sapply(x,length)

options(scipen = 999)

data.d$totl <- data.d$budget/data.d$denom

#ADD LETTERS TO REMOVE DUPLICATES! ##
test <- duplicated(data.d$totl)
n <- 1:length(data.d$totl[test])

sam <- sample(letters[1:26], length(n), FALSE)

data.d$totl[test] <- paste0(data.d$totl[test], sam)

if(sum(duplicated(data.d$totl)) > 1 ) print("STOP NAMES DUPLICATED!")
####################################################
names(x) <- data.d$totl



x1 = lapply(names(x), function(name){
  data.frame(amount = name,
             country = x[[name]])
})

master <- do.call("rbind", x1)
master$country <- as.character(master$country)

##Remove letter used to create unique values
master$amount <- gsub(pattern = "[a-z]+$","",master$amount)
master$amount <- as.numeric(as.character(master$amount))
master$country[master$country == "Cameroun"] <- "Cameroon"
master$country <- countrycode(master$country, origin = "country.name",
                                destination = "country.name", warn = TRUE)

master <- master %>% 
            group_by(country) %>%
            summarize(amount = sum(amount))

tab <- arrange(master, desc(amount))


knitr::kable(tab) 
```

# Scatterplot w/ CA score and country budget for AFRICA

```{r, echo = FALSE}
#--------CREATE DF FOR EXPENDITURES BY COUNTRY AND MERGE CA score
africa <- filter(data, Region == "Africa" & assCountry == 1)

#Get expenditure data 
test.c <- colnames(africa) %in% NA
africa <- africa[!test.c]

data.d <- select(africa, country, budget, donor)
data.d <- filter(data.d, !is.na(budget))

x <- strsplit(data.d$country,",")

data.d$denom <- sapply(x,length)

options(scipen = 999)

data.d$totl <- data.d$budget/data.d$denom

#HACK TO REMOVE DUPS################################
test <- duplicated(data.d$totl)
n <- 1:length(data.d$totl[test])
data.d$totl[test] <- data.d$totl[test] + n/100
####################################################

names(x) <- data.d$totl

x1 = lapply(names(x), function(name){
  data.frame(amount = name,
             country = x[[name]])
})

master <- do.call("rbind", x1)
master$country <- as.character(master$country)
master$amount <- as.numeric(as.character(master$amount))
master$country <- countrycode(master$country, origin = "country.name",
                                destination = "country.name", warn = TRUE)

master <- master %>% 
            group_by(country) %>%
            summarize(amount = sum(amount))

master <- merge(master, ca, by.x = "country", by.y = "country",
                all = TRUE)

master$country <- countrycode(master$country, origin = "country.name",
                              destination = "iso3c")

master <- filter(master, !is.na(amount))
master <- filter(master, !is.na(score))
master$score <- as.numeric(master$score)

n = .15
master$score.g[master$score < (mean(master$score) - n*sd(master$score)) &
               master$amount < (mean(master$amount) - n*sd(master$amount))] <- "low score, low support"


master$score.g[master$score < (mean(master$score) - n*sd(master$score)) &
               master$amount > (mean(master$amount) - n*sd(master$amount))] <- "low score, mid-high support"


master$score.g[master$score > (mean(master$score) - n*sd(master$score)) &
               master$amount < 3000000] <- "mid-high score, low support"
master$score.g[master$score > (mean(master$score) - n*sd(master$score)) &
               master$amount > 3000000] <- "mid-high score, mid-high support"


master$score.g[is.na(master$score.g)] <- NA
master$amount.mil <- master$amount/1000000

ggplot(master, aes(x=amount.mil, y=score)) +
    geom_point(aes(col = score.g), size = 5) + 
    #scale_color_grey(start = .2, end = 1) +
    scale_color_manual(values = c("red","lightgrey","darkgrey","black")) +
    geom_text(aes(label=country), size = 3, vjust = -.25, hjust = -.25) +
    theme(legend.position="bottom",
          legend.title = element_blank()) +
    guides(colour = guide_legend(override.aes = list(size=5), 
                                 nrow = 2, byrow = TRUE)) +
    labs(x = "Total Amount Spent in Millions (active 2015)", y = "Country Assessment Score (2013)") +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank()) 

```
